spring:
 activiti:
  check-process-definitions: false #自动检查、部署流程定义文件
  database-schema-update: true #自动更新数据库结构
  #流程定义文件存放目录
  process-definition-location-prefix: classpath:/processes/
  #process-definition-location-suffixes: #流程文件格式
 devtools:
  livereload:
   enabled: true
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   naming:
    physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 datasource:
  url: jdbc:mysql://localhost:3306/act?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&nullCatalogMeansCurrent=true
  username: root
  password: root
  driverClassName: com.mysql.cj.jdbc.Driver


    #自动部署文件路径后缀
#   process-definition-location-prefix: classpath:/processes/
#   process-definition-location-suffixes:
#      - **.bpmn
#      - **.bpmn20.xml
logging:
 level:
  root: DEBUG
  org.springframework.security: DEBUG
 pattern:
  console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %yellow(at %class.%method) \\(%file:%line\\) %n%clr(>>>>>>) %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
student:
 name: vicky
 age: 12